import Container from '@/components/ui/Container';

export default function Liability() {
  return (
    <section
      id="liability"
      className="py-32 border-y border-slate-900 bg-slate-950 relative z-10"
    >
      <Container>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 items-start">
          <div className="lg:col-span-6">
            <span className="text-[10px] font-mono font-black uppercase tracking-widest text-cyan-400 bg-cyan-400/5 px-2.5 py-1 rounded border border-cyan-400/20">
              The Regulatory Hazard Matrix
            </span>
            <h2 className="text-3xl sm:text-5xl lg:text-6xl font-mono font-black text-white mt-6 uppercase tracking-tight leading-[1.05]">
              AI Agent declarations carry absolute{' '}
              <span className="text-cyan-400">corporate liability.</span>
            </h2>
          </div>

          <div className="lg:col-span-6 space-y-6 text-slate-400 text-sm sm:text-lg leading-relaxed font-sans font-light">
            <p className="font-mono font-bold text-slate-200 uppercase tracking-wider text-xs bg-slate-900/40 p-3 border-l-2 border-cyan-400">
              CASE REFERENCE OVERVIEW // THE AIR CANADA LITIGATION PRECEDENT
            </p>
            <p>
              When a consumer assistant chatbot erroneously promised custom
              refund options to an active traveler, the parent corporation
              attempted to reject the obligation by stating that its backend
              internal database structures overrode the AI agent statements.
            </p>
            <p>
              The high court strictly rejected the defense, ruling that
              companies are fully liable for all declarations generated by their
              AI models. With the incoming{' '}
              <span className="text-white font-semibold">
                EU AI Act enforcement timeline (effective August 2026)
              </span>{' '}
              carrying catastrophic fines up to{' '}
              <span className="text-amber-500 font-bold font-mono">
                Nordic Scale: €35 Million or 7% of total global turnover
              </span>
              , unverified, modifiable databases are a massive corporate
              liability.
            </p>
          </div>
        </div>
      </Container>
    </section>
  );
}
